version: '3.1'

services:
  app:
    image: node:12-alpine
    container_name: gobarber_app
    env_file:
      - .env
    ports:
      - "3333:3333"
    command: sh -c "yarn && yarn typeorm migration:run && yarn dev"
    working_dir: /app
    depends_on:
      - pg_database
    volumes:
      - ".:/app"
    expose:
      - "3333"

  pg_database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobarber
    ports:
      - "5432:5432"
    container_name: gobarber_postgres

  mongo_database:
    image: mongo
    ports:
      - "27017:27017"
    container_name: gobarber_mongo

  redis:
    image: redis:alpine
    container_name: gobarber_redis
    ports:
      - "6379:6379"
